PMM-7187 Tests for Inventory Page to check Agent Status
percona/grafana-dashboards pull request #1088
Opened 2021-01-05 09:28 UTC by IvanaBrecherova

2021-01-11 08:14 UTC, puneet0191 requested changes

2021-01-11 08:14 UTC, puneet0191 commented on pmm-app/tests/pages/pmmInventoryPage.js
> +  async getCountOfRunning() {
Change this name to getCountofRunningAgents

2021-01-11 08:14 UTC, puneet0191 commented on pmm-app/tests/verifyPMMInventory_test.js
> +    const countBefore = await pmmInventoryPage.getCountOfItems();
This should be total agents configured/added, this is confusing for name

2021-01-11 09:34 UTC, IvanaBrecherova commented
Checked on UI test job: https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/6220/tests

2021-01-11 18:41 UTC, atymchuk submitted a review, later dismissed
All nits, approved

2021-01-11 18:41 UTC, atymchuk commented on pmm-app/tests/pages/pmmInventoryPage.js
> +  async getCountofRunningAgents() {
```suggestion
  async getCountOfRunningAgents() {
```

2021-01-11 18:41 UTC, atymchuk commented on pmm-app/tests/verifyPMMInventory_test.js
> +    const countOfRunning = await pmmInventoryPage.getCountofRunningAgents();
```suggestion
    const countOfRunning = await pmmInventoryPage.getCountOfRunningAgents();
```

2021-01-11 18:41 UTC, atymchuk commented on pmm-app/tests/pages/pmmInventoryPage.js
> +  async getCountofRunningAgents() {
It's a typo I believe

2021-01-11 18:41 UTC, atymchuk commented on pmm-app/tests/verifyPMMInventory_test.js
> +    // Need countOfPMMAgentType because agents that have Type PMM Agent don't have status. We need subtrack it
```suggestion
    // Need countOfPMMAgentType because agents that have Type PMM Agent don't have status. We need to subtract it
```

2021-01-12 12:32 UTC, puneet0191 approved these changes

2021-01-12 12:56 UTC, merged