PMM-7406 IA settings tests
percona/grafana-dashboards pull request #1111
Opened 2021-02-01 17:50 UTC by yurkovychv

2021-02-04 09:58 UTC, puneet0191 commented on pmm-app/tests/databaseChecks_test.js
> +Feature('Database Failed Checks').retry(3);
why?

2021-02-04 10:10 UTC, yurkovychv commented on pmm-app/tests/databaseChecks_test.js
> +Feature('Database Failed Checks').retry(3);
testing it out

2021-02-05 15:19 UTC, puneet0191 approved these changes

2021-02-06 09:02 UTC, atymchuk requested changes

2021-02-08 09:21 UTC, yurkovychv commented on pmm-app/codeceptConfigHelper.js
> +    const conflictGroup = files.filter((value) => value.includes('PMMSettings')
thanks done

2021-02-08 09:21 UTC, yurkovychv commented on pmm-app/codeceptConfigHelper.js
> +    const otherGroup = files.filter((val) => (conflictGroup.indexOf(val) === -1));
much better, thanks

2021-02-08 09:21 UTC, yurkovychv commented on pmm-app/codeceptConfigHelper.js
> +      otherGroup,
renamed vars

2021-02-08 16:27 UTC, atymchuk approved these changes

2021-02-09 09:47 UTC, merged