PMM-6671 add HAProxy add instance form
percona/grafana-dashboards pull request #1123
Opened 2021-02-08 10:44 UTC by lunaticusgreen

2021-02-12 09:56 UTC, tiagomotasantos requested changes

2021-02-12 09:56 UTC, tiagomotasantos commented on pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/HAProxyConnectionDetails/HAProxyConnectionDetails.tsx
> +      <div className={styles.labelWrapper} data-qa="service_name-label">
```suggestion
      <div className={styles.labelWrapper} data-qa="service-name-label">
```

2021-02-12 09:56 UTC, tiagomotasantos commented on pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/HAProxyConnectionDetails/HAProxyConnectionDetails.tsx
> +      <TextInputField name="service_name" placeholder={Messages.form.placeholders.mainDetails.serviceName} />
```suggestion
      <TextInputField name="service-name" placeholder={Messages.form.placeholders.mainDetails.serviceName} />
```

2021-02-12 10:20 UTC, lunaticusgreen commented on pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/HAProxyConnectionDetails/HAProxyConnectionDetails.tsx
> +      <div className={styles.labelWrapper} data-qa="service_name-label">
done

2021-02-12 10:21 UTC, lunaticusgreen commented on pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/HAProxyConnectionDetails/HAProxyConnectionDetails.tsx
> +      <TextInputField name="service_name" placeholder={Messages.form.placeholders.mainDetails.serviceName} />
done

2021-02-12 10:26 UTC, tiagomotasantos submitted a review, later dismissed

2021-02-17 11:26 UTC, tiagomotasantos approved these changes

2021-02-17 18:32 UTC, tiagomotasantos approved these changes

2021-02-18 15:55 UTC, tiagomotasantos approved these changes

2021-02-18 16:10 UTC, merged