Nightly-job
percona/grafana-dashboards pull request #1130
Opened 2021-02-10 12:14 UTC by IvanaBrecherova

2021-02-11 12:15 UTC, puneet0191 requested changes

2021-02-11 12:15 UTC, puneet0191 commented on pmm-app/tests/verifyAWSRDSMySQLInstance_test.js
> +    // So many graphs have No Data - skipping the check
please create a ticket to investigate, and add that as To-Do, so many graphs is really not clear enough

2021-02-11 12:15 UTC, puneet0191 commented on pmm-app/tests/verifyInsightDashboards_test.js
> +    // increasing to 15 because of failings
The same here, please create one single ticket to add these skips in checks.

2021-02-11 12:24 UTC, IvanaBrecherova commented
https://jira.percona.com/browse/PMM-7502 task for future investigation.

2021-02-11 14:12 UTC, yurkovychv commented
@IvanaBrecherova please change the base branch to `release/2.15`

2021-02-12 08:22 UTC, puneet0191 approved these changes

2021-02-12 08:30 UTC, puneet0191 approved these changes

2021-02-12 08:54 UTC, merged