PMM-7585
percona/grafana-dashboards pull request #1165
Opened 2021-03-01 12:20 UTC by IvanaBrecherova

2021-03-02 10:30 UTC, puneet0191 requested changes
Please pull changes from upstream PMM-2.0, upstream release/2.16 also address the comment left for retry

2021-03-02 10:30 UTC, puneet0191 commented on pmm-app/tests/verifyPMMSettingsPageFunctionality_test.js
> +}).retry(0);
Does not make sense to have a retry 0

2021-03-03 12:05 UTC, yurkovychv approved these changes

2021-03-03 12:24 UTC, puneet0191 requested changes

2021-03-03 12:24 UTC, puneet0191 commented on Jenkinsfile
> +                            sudo git clone --single-branch --branch PMM-7482 https://github.com/percona/pmm-qa.git .
change the branch to master, the chrome script has been merged already

2021-03-04 08:45 UTC, puneet0191 approved these changes

2021-03-04 08:49 UTC, puneet0191 requested changes

2021-03-04 08:49 UTC, puneet0191 commented on pmm-app/package.json
>      "e2e:local": "docker run --net=host --name codecept -v $PWD:/tests -v $PWD/node_modules:/node_modules codeception/codeceptjs:2.6.1 codeceptjs run-multiple parallel --all --debug --steps -c pr-loc
@IvanaBrecherova change this also please, we can not use docker based runs any more

2021-03-04 09:35 UTC, merged