PMM-7723 update grafana dashboards branching and guideline
percona/grafana-dashboards pull request #1251
Opened 2021-08-05 18:25 UTC by adivinho

2021-08-05 19:17 UTC, denisok requested changes
nice changes!

2021-08-05 19:17 UTC, denisok commented on CONTRIBUTING.md
> +== Submitting a Bug
we have issues enabled in this project as well, so maybe make jira optional.

2021-08-05 19:17 UTC, denisok commented on CONTRIBUTING.md
>  1.  Find the task in [JIRA](https://jira.percona.com/issues/?jql=project+%3D+PMM+AND+component+%3D+%22Grafana+Dashboards%22) or create a new task. Use a component filter Grafana Dashboards.
or issue here in GH

2021-08-05 19:17 UTC, denisok commented on CONTRIBUTING.md
> +4.  Create a new branch for your task. Name it using the following pattern: [JIRA_ISSUE_ID]-[username]-[short_title]. For example: PMM-5053-dbazhenov-tooltip .
we can relax branch naming, it is up to ppl how to call hem, we could recommend as best practice to mention issue number or just short desc

2021-08-05 19:17 UTC, denisok commented on CONTRIBUTING.md
> +We're looking forward to your contributions and hope to hear from you soon on our [Forums](https://forums.percona.com) and [Discord](https://discord.gg/mQEyGPkNbR).
same for discord link

2021-08-05 19:18 UTC, denisok commented
adding Paul to check lang, I seen couple of issues but he is better for that

2021-08-06 09:17 UTC, PaulJacobs-percona approved these changes

2021-08-06 12:11 UTC, denisok approved these changes

2021-08-06 15:10 UTC, merged