PMM-9356-add-experimental-environment-dashboards-to-pmm
percona/grafana-dashboards pull request #1295
Opened 2021-12-24 08:58 UTC by anton-bystrov

[PMM-9356](https://jira.percona.com/browse/PMM-9356) Add two experimental dashboards from [blog](https://www.percona.com/blog/new-experimental-environment-dashboards-for-percona-monitoring-and-management/)

2021-12-24 09:18 UTC, nikita-b approved these changes

2021-12-24 10:23 UTC, rnovikovP submitted a review, later dismissed

2021-12-24 10:27 UTC, rasika-chivate requested changes
Please change the content as follows:

**About Dashboard**
The Environment Summary Dashboard provides an at-a-glance view specific to the selected environment, including an overview of the services and nodes running in that environment.

To provide your feedback about the Dashboard, visit our forum.

For the **Environments Overview**:

The Dashboard provides the user with a high-level view of all the environments.
To provide your feedback about the Dashboard, visit our forum.

Also, add PostgreSQL on these dashboards...

**Overview**

Percona Monitoring and Management (PMM) is a free and open-source platform for managing and monitoring MySQL and MongoDB performance and provides time-based analysis to ensure that your data works as efficiently as possible.

2021-12-27 08:15 UTC, rasika-chivate approved these changes

2021-12-30 17:19 UTC, denisok approved these changes

2021-12-30 17:19 UTC, merged