PMM-9234-QAN-fix-isHistogramAvailable: add groupBy
percona/grafana-dashboards pull request #1302
Opened 2022-01-26 10:15 UTC by solovevayaroslavna

fixing the Internal server error in some cases when grouping by User Name/Database is used in QAN
https://jira.percona.com/browse/PMM-9234

2022-01-26 11:16 UTC, fabio-silva submitted a review, later dismissed

2022-01-26 14:17 UTC, tiagomotasantos requested changes
Good solution!! Just fix build errors and it's good to go.

2022-01-27 09:26 UTC, tiagomotasantos approved these changes

2022-01-27 09:36 UTC, fabio-silva approved these changes

2022-01-31 19:53 UTC, merged