PMM-10244 Vacuum Monitoring Dashboard
percona/grafana-dashboards pull request #1361
Opened 2022-07-11 12:40 UTC by gen1us2k

[PMM-10244](https://jira.percona.com/browse/PMM-10244)

2022-07-11 12:44 UTC, gen1us2k commented
I'm not sure I placed a dashboard on the correct folder for PoC of Vacuum Monitoring feature.

2022-07-11 13:02 UTC, anton-bystrov requested changes
What about variables -

2022-07-11 13:02 UTC, anton-bystrov commented on dashboards/PostgreSQL/PostgreSQL_Vacuum_Monitoring.json
> +  "editable": true,
Here change to "false" please

2022-07-19 07:52 UTC, solovevayaroslavna commented on dashboards/PostgreSQL/PostgreSQL_Vacuum_Monitoring.json
> +            "uid": "PA58DA793C7250F1B"
@anton-bystrov can you check datasource? Don't we need to use Metrics here?
`"datasource": "Metrics"`

2022-07-19 07:52 UTC, solovevayaroslavna commented on dashboards/PostgreSQL/PostgreSQL_Vacuum_Monitoring.json
> +            "uid": "PA58DA793C7250F1B"
@anton-bystrov sorry, I see, you left a comment highter

2022-09-09 08:49 UTC, JiriCtvrtka approved these changes

2022-09-09 08:49 UTC, anton-bystrov approved these changes

2022-09-12 08:11 UTC, JiriCtvrtka approved these changes

2022-09-12 08:11 UTC, merged