PMM-10608 experimental home dashboard bugfix
percona/grafana-dashboards pull request #1382
Opened 2022-09-06 07:20 UTC by anton-bystrov

[PMM-10608](https://jira.percona.com/browse/PMM-10608) Fix issues with node_name and environment filters, upgrade graph to timeseries panels. Change types High CPU and High Disk Queue panels.
![image](https://user-images.githubusercontent.com/83747830/188571380-3d3bf4a6-7e45-4766-88a6-d391778d8b04.png)
![image](https://user-images.githubusercontent.com/83747830/188571613-8e90b87a-f2e7-4baf-add3-f85a96d7fb4f.png)

2022-09-06 07:22 UTC, dygksy requested changes
@anton-bystrov can we adjust the value alignment? Right alignment is possible for the values?

2022-09-06 07:33 UTC, anton-bystrov commented
> @anton-bystrov can we adjust the value alignment? Right alignment is possible for the values?

Yes, but empty panel it seems this: 
![image](https://user-images.githubusercontent.com/83747830/188574280-eb0efdb8-7b62-49ad-8aca-34363e40d5ed.png)

2022-09-08 14:22 UTC, dygksy submitted a review, later dismissed

2022-09-14 13:07 UTC, dygksy approved these changes

2022-09-14 13:22 UTC, merged