PMM-12165 Changed queries for new plugin
percona/grafana-dashboards pull request #1509
Opened 2023-06-02 07:30 UTC by anton-bystrov

PMM-12165 

https://github.com/Percona-Lab/pmm-submodules/pull/3293

This PR:
1/ solves the problem of broken queries, which led to the absence of metrics on Environment Dashboard
2/ replaces boomtable with the native table plugin

This is how the Environment Overview looks now:
<img width="1728" alt="Screenshot 2023-06-09 at 03 43 43" src="https://github.com/percona/grafana-dashboards/assets/81549/be1fba5a-c1f0-4663-bc27-373f573b7e6e">

<img width="1728" alt="Screenshot 2023-06-09 at 03 44 06" src="https://github.com/percona/grafana-dashboards/assets/81549/0021625a-bd30-4213-a988-4f433639b55b">

2023-06-02 09:25 UTC, 0leksii submitted a review, later dismissed

2023-06-02 12:35 UTC, atymchuk requested changes

2023-06-02 12:35 UTC, atymchuk commented on dashboards/Experimental/Environments_Overview.json
> +          },
This looks a bit strange. Why is it broken up by letters?

2023-06-02 12:35 UTC, atymchuk commented on dashboards/Experimental/Environments_Overview.json
> +          "datasource": {
Can this be one string, e.g. `"datasource": "-- Mixed --"`?

2023-06-02 12:35 UTC, atymchuk commented on dashboards/Experimental/Environments_Overview.json
> +            "builderOptions": {
Can this be just one string? It doesn't feel right either.

2023-06-02 12:35 UTC, atymchuk commented on dashboards/Experimental/Environments_Overview.json
> +          "$$hashKey": "object:73",
We need to remove those $$hasKey entries - they are redundant and not good for maintenance.

2023-06-09 00:15 UTC, atymchuk submitted a review, later dismissed

2023-06-09 12:10 UTC, BupycHuk submitted a review, later dismissed

2023-06-13 09:53 UTC, merged