PMM-6375 sign out
percona/grafana-dashboards pull request #929
Opened 2020-08-24 08:22 UTC by nicolalamacchia

2020-08-24 09:04 UTC, lunaticusgreen approved these changes
LGTM

2020-08-24 21:22 UTC, atymchuk commented on pmm-app/package.json
> +    "@types/jest": "^26.0.10",
This is devDependency

2020-08-25 10:48 UTC, tiagomotasantos approved these changes

2020-08-25 19:35 UTC, atymchuk commented
@nicolalamacchia Where did the code disappear ?:(? My comments go to dev/null )

2020-08-26 09:04 UTC, atymchuk requested changes

2020-08-26 09:04 UTC, atymchuk commented on pmm-app/src/shared/components/helpers/validators.ts
> +  compose: (...validators) => (value, values) => validators.reduce(
Solved in a different branch, no worries.

2020-08-26 14:32 UTC, nicolalamacchia commented on pmm-app/package.json
> +    "@emotion/core": "^10.0.35",
Removing this break the build, this solves some TypeScript checks apparently, so I'm keeping it for now (it's outside the scope of this PR)

2020-08-26 15:20 UTC, atymchuk approved these changes

2020-08-27 09:10 UTC, merged