PMM-6492 add clusters
percona/grafana-dashboards pull request #942
Opened 2020-08-28 22:07 UTC by lunaticusgreen

2020-08-31 14:25 UTC, tiagomotasantos requested changes

2020-08-31 14:25 UTC, tiagomotasantos commented on pmm-app/src/pmm-dbaas/DBaaS.messages.ts
> +    addAction: 'Add new K8s Cluster',
Change to "Add new Kubernetes Cluster" (I know it's not what is on the design but makes it more consistent)

2020-08-31 14:25 UTC, tiagomotasantos commented on pmm-app/src/shared/components/Elements/Modal/Modal.styles.ts
> +      padding: 16px;
`theme.spacing.sm` or `theme.spacing.md` will do

2020-09-01 08:01 UTC, tiagomotasantos requested changes

2020-09-01 08:01 UTC, tiagomotasantos commented on pmm-app/src/pmm-dbaas/components/Kubernetes/KubernetesInventory.tsx
> +        <AddNewClusterButton />
Move this above delete button (so add button comes first)

2020-09-01 12:58 UTC, tiagomotasantos approved these changes

2020-09-01 15:40 UTC, nicolalamacchia requested changes

2020-09-02 12:04 UTC, nicolalamacchia approved these changes

2020-09-22 11:25 UTC, merged