PMM-6518 Dashboards datasource name change
percona/grafana-dashboards pull request #992
Opened 2020-10-08 17:03 UTC by adivinho

- [ ] https://github.com/Percona-Lab/pmm-submodules/pull/1162

2020-10-12 09:48 UTC, AlekSi commented
![image](https://user-images.githubusercontent.com/11512/95732192-2bcf7080-0c89-11eb-9f6c-0c91db0024a9.png)

Why some lines change data source to `null` and some to `"Metrics"`?

2020-10-12 10:17 UTC, adivinho commented
> Why some lines change data source to `null` and some to `"Metrics"`?

Data source 'null' means default. It's used in elements. 
But variables have no default data source.

![Screenshot_20201012_131603](https://user-images.githubusercontent.com/25184101/95735225-38ee5e80-0c8d-11eb-8e5c-3e66036a673a.png)

2020-10-12 23:57 UTC, atymchuk requested changes

2020-10-12 23:57 UTC, atymchuk commented on dashboards/Advanced_Data_Exploration.json
> +                "datasource": "Metrics",
Can we document cases when the `datasource` takes the value of `null` vs `Metrics`.

2020-10-12 23:59 UTC, atymchuk commented
> > Why some lines change data source to `null` and some to `"Metrics"`?
> 
> Data source 'null' means default. It's used in elements.
> But variables have no default data source.

Where do we define that Metrics is the default datasource?

2020-10-13 06:06 UTC, adivinho commented
> > > Why some lines change data source to `null` and some to `"Metrics"`?
> > 
> > 
> > Data source 'null' means default. It's used in elements.
> > But variables have no default data source.
> 
> Where do we define that Metrics is the default datasource from now on?

It's done here 
https://github.com/percona/pmm-server/pull/234/files#diff-6d9daaf92d20be62aca45159d3c7d75b85323ed98a6c9cf22fb87c7610acee3fR175

2020-10-13 16:45 UTC, atymchuk approved these changes

2020-10-19 14:53 UTC, merged